# Generated by Django 5.2.11 on 2026-02-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('etf', 'ETF'), ('stock', 'Stock'), ('bond', 'Bond'), ('gic', 'GIC'), ('cash', 'Cash')], max_length=10)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=3)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('geography', models.CharField(blank=True, default='', max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['ticker'],
            },
        ),
    ]
