# Generated by Django 5.2.11 on 2026-03-01 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('condo', 'Condo (divided co-ownership)'), ('condo_undivided', 'Condo (undivided co-ownership)'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('land', 'Vacant land'), ('cottage', 'Cottage / Secondary residence'), ('commercial', 'Commercial property')], max_length=20, verbose_name='property type')),
                ('usage', models.CharField(choices=[('primary', 'Primary residence'), ('secondary', 'Secondary residence'), ('rental', 'Rental property'), ('commercial', 'Commercial')], max_length=20, verbose_name='usage')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('province', models.CharField(default='QC', max_length=50, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='purchase price')),
                ('purchase_date', models.DateField(verbose_name='purchase date')),
                ('welcome_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='welcome tax paid')),
                ('notary_fees_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='notary fees at purchase')),
                ('current_valuation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='current valuation')),
                ('valuation_date', models.DateField(verbose_name='valuation date')),
                ('municipal_assessment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='municipal assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_periods', to='real_estate.property')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=200, verbose_name='lender')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='original principal')),
                ('annual_rate', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='annual interest rate (%)')),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=20, verbose_name='rate type')),
                ('amortization_years', models.PositiveSmallIntegerField(default=25, verbose_name='amortization (years)')),
                ('term_years', models.PositiveSmallIntegerField(default=5, verbose_name='term (years)')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('accelerated_biweekly', 'Accelerated bi-weekly')], default='monthly', max_length=30, verbose_name='payment frequency')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('insurance_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='mortgage insurance premium')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgages', to='real_estate.property')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='invitee email')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='down payment')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='real_estate.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Can this owner edit property details?', verbose_name='can edit property')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='down payment contributed')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='real_estate.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property ownership',
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='PropertyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('renovation', 'Renovation / Improvement'), ('repair', 'Repair / Maintenance'), ('property_tax', 'Property tax'), ('insurance', 'Insurance'), ('condo_fees', 'Condo fees'), ('other', 'Other')], max_length=20, verbose_name='type')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('date', models.DateField(verbose_name='date')),
                ('increases_acb', models.BooleanField(default=False, help_text='Capital improvements increase the adjusted cost base for tax purposes.', verbose_name='increases cost base')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='real_estate.property')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to='real_estate.propertyownership')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(related_name='properties', through='real_estate.PropertyOwnership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='value')),
                ('date', models.DateField(verbose_name='date')),
                ('source', models.CharField(choices=[('manual', 'Manual estimate'), ('appraisal', 'Professional appraisal'), ('municipal', 'Municipal assessment'), ('comparable', 'Comparable sales')], default='manual', max_length=20, verbose_name='source')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='real_estate.property')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipPeriodShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ownership share (%)')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='real_estate.ownershipperiod')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_shares', to='real_estate.propertyownership')),
            ],
            options={
                'unique_together': {('period', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='MortgagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveIntegerField(verbose_name='payment number')),
                ('date', models.DateField(verbose_name='payment date')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total payment')),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='principal portion')),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='interest portion')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance after payment')),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='real_estate.mortgage')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_payments', to='real_estate.propertyownership')),
            ],
            options={
                'ordering': ['payment_number'],
                'unique_together': {('mortgage', 'payment_number')},
            },
        ),
    ]
