# Generated by Django 5.2.11 on 2026-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinvitation',
            name='share_pct',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='ownership share (%)'),
        ),
    ]
