# Generated by Django 5.2.11 on 2026-03-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_add_share_pct_to_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('municipal', 'Municipal tax'), ('school', 'School tax')], max_length=20, verbose_name='tax type')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'property tax',
                'verbose_name_plural': 'property taxes',
                'ordering': ['-year', 'tax_type'],
                'unique_together': {('property', 'tax_type', 'year')},
            },
        ),
    ]
