# Generated by Django 5.2.11 on 2026-03-03 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_propertytax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('invitation_sent', 'Invitation sent'), ('invitation_accepted', 'Invitation accepted'), ('co_owner_removed', 'Co-owner removed'), ('expense_added', 'Expense added'), ('expense_updated', 'Expense updated'), ('expense_deleted', 'Expense deleted'), ('tax_added', 'Tax added'), ('tax_updated', 'Tax updated'), ('tax_deleted', 'Tax deleted'), ('valuation_added', 'Valuation added'), ('valuation_updated', 'Valuation updated'), ('valuation_deleted', 'Valuation deleted'), ('property_updated', 'Property updated')], max_length=30, verbose_name='action')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='real_estate.property')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='real_estate_recipie_701104_idx')],
            },
        ),
    ]
