# Generated by Django 5.2.11 on 2026-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_propertynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('CAD', 'Canadian Dollar (CAD)'), ('EUR', 'Euro (EUR)')], default='CAD', max_length=3, verbose_name='currency'),
        ),
    ]
