# Generated by Django 5.2.11 on 2026-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_add_currency_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='borrower_insurance_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='borrower insurance rate (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('FR', 'France')], default='CA', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('mixed', 'Mixed (taux mixte)')], default='fixed', max_length=20, verbose_name='rate type'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='expense_type',
            field=models.CharField(choices=[('renovation', 'Renovation / Improvement'), ('repair', 'Repair / Maintenance'), ('property_tax', 'Property tax'), ('insurance', 'Insurance'), ('condo_fees', 'Condo fees'), ('charges_copro', 'Charges de copropriété'), ('assurance_emprunteur', 'Assurance emprunteur'), ('other', 'Other')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='propertytax',
            name='tax_type',
            field=models.CharField(choices=[('municipal', 'Municipal tax'), ('school', 'School tax'), ('taxe_fonciere', 'Taxe foncière'), ('taxe_habitation', "Taxe d'habitation"), ('ifi', 'IFI (wealth tax)')], max_length=20, verbose_name='tax type'),
        ),
    ]
