# Generated by Django 5.2.11 on 2026-03-11 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_add_france_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyexpense',
            name='proof_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='proof document link'),
        ),
        migrations.CreateModel(
            name='MortgageRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_annual_rate', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='new annual rate (%)')),
                ('new_rate_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('mixed', 'Mixed (taux mixte)')], default='', max_length=20, verbose_name='new rate type')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('is_simulation', models.BooleanField(default=False, verbose_name='simulation only')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_changes', to='real_estate.mortgage')),
            ],
            options={
                'verbose_name': 'mortgage rate change',
                'verbose_name_plural': 'mortgage rate changes',
                'ordering': ['effective_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly rent')),
                ('agency_fee_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage taken by rental management agency', max_digits=5, verbose_name='agency fee (%)')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_incomes', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'rental income',
                'verbose_name_plural': 'rental incomes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnerMonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monthly amount')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_payments', to='real_estate.mortgage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='real_estate.propertyownership')),
            ],
            options={
                'verbose_name': 'owner monthly payment',
                'verbose_name_plural': 'owner monthly payments',
                'ordering': ['effective_date'],
                'unique_together': {('mortgage', 'owner', 'effective_date')},
            },
        ),
    ]
