# Generated by Django 5.2.11 on 2026-03-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_rate_rental_payments_prooflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertynotification',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='real_estate.propertyinvitation'),
        ),
        migrations.AlterField(
            model_name='propertynotification',
            name='verb',
            field=models.CharField(choices=[('invitation_sent', 'Invitation sent'), ('invitation_received', 'Invitation received'), ('invitation_accepted', 'Invitation accepted'), ('co_owner_removed', 'Co-owner removed'), ('expense_added', 'Expense added'), ('expense_updated', 'Expense updated'), ('expense_deleted', 'Expense deleted'), ('tax_added', 'Tax added'), ('tax_updated', 'Tax updated'), ('tax_deleted', 'Tax deleted'), ('valuation_added', 'Valuation added'), ('valuation_updated', 'Valuation updated'), ('valuation_deleted', 'Valuation deleted'), ('property_updated', 'Property updated')], max_length=30, verbose_name='action'),
        ),
    ]
