# Generated by Django 5.2.11 on 2026-03-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_invitation_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='current valuation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='valuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='valuation date'),
        ),
    ]
